# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.13.02

inherit perl-module

S=${WORKDIR}/FCGI-ProcManager-0.17
DESCRIPTION="A FastCGI process manager"
SRC_URI="mirror://cpan/authors/id/J/JU/JURACH/FCGI-ProcManager-0.17.tar.gz"
HOMEPAGE="http://www.cpan.org/modules/by-authors/id/J/JU/JURACH/${P}.readme"

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="alpha amd64 arm hppa ia64 m68k mips ppc ppc64 ppc-macos s390 sh sparc sparc-fbsd x86 x86-fbsd"

