# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.13.02

inherit perl-module

#S=${WORKDIR}/${P}
DESCRIPTION="Catalyst plugin for CGI::Untaint."
SRC_URI="mirror://cpan/authors/id/T/TJ/TJC/${P}.tar.gz"
RESTRICT="nomirror"
HOMEPAGE="http://search.cpan.org/dist/${PN}/"

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="alpha amd64 arm hppa ia64 m68k mips ppc ppc64 ppc-macos s390 sh sparc x86 x86-fbsd"

DEPEND="
	dev-perl/Catalyst-Runtime
	>=dev-perl/CGI-Untaint-1.20
"
